theme: jekyll-theme-slate
title: [AlchemistCMS]
description: [An opensource CMS built using Elixir-lang, OTP and Phoenix framework]

github:
  zip_url: https://github.com/AlchemistCMS
  another_url: https://github.com/AlchemistCMS
