theme: jekyll-theme-slate
title: AlchemistCMS - A Realtime CMS.
description: An opensource CMS with realtime features built using Elixir-lang OTP and Phoenix framework

github:
  zip_url: https://github.com/AlchemistCMS
  another_url: https://github.com/AlchemistCMS
